source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.4'
inhibit_all_warnings!

target :MenuSampler do
	pod 'BRCocoaLumberjack',        '~> 2.0'
	pod 'BRStyle/Core',             '~> 0.10.0'
	pod 'RestKit/ObjectMapping',	'~> 0.24.0'
	pod 'MenuKit/All',              :path => '../'
	
	target :MenuSamplerTests do
		pod 'OCHamcrest',			'~> 4.1'
		pod 'OCMock',				'~> 3.1'
		pod 'CocoaHTTPServer',		'~> 2.3'
		pod 'RoutingHTTPServer', 	'~> 1.0'
	end
	
end
