source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.4'

target :MenuSampler do
	pod 'BRMenu', :subspecs => ['Core', 'RestKit', 'AFNetworking', 'UI'], 
		:path => '../'
	pod 'Color-Picker-for-iOS', 	'~> 2.0'
	pod 'MAObjCRuntime', 			'~> 0.0.1'
	
	target :MenuSamplerTests do
		pod 'OCHamcrest',			'~> 4.1', :inhibit_warnings => true
		pod 'OCMock',				'~> 3.1'
		pod 'CocoaHTTPServer',		'~> 2.3', :inhibit_warnings => true
		pod 'RoutingHTTPServer', 	'~> 1.0', :inhibit_warnings => true
	end
	
end
