source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.1'

inhibit_all_warnings!

target :Menu do
	pod 'AFNetworking/Serialization', '~> 2.5'
	pod 'BRCocoaLumberjack',		  '~> 2.0'
	pod 'BREnvironment',			  '~> 1.1'
	pod 'BRLocalize',				  '~> 0.9'
	pod 'BRPDFImage',				  '~> 1.0'
	pod 'MAObjCRuntime', 			  '~> 0.0.1'
	pod 'Masonry',					  '~> 0.6'
	pod 'RestKit/ObjectMapping',	  '~> 0.24'
	pod 'BRStyle/Core',               :path => '../../BRStyle'
	
	target :MenuTests do
		pod 'AFNetworking',           '~> 2.5'
		pod 'OCHamcrest',			  '~> 4.1'
		pod 'OCMock',				  '~> 3.1'
		pod 'CocoaHTTPServer',		  '~> 2.3'
		pod 'RoutingHTTPServer', 	  '~> 1.0'
	end
	
end
